### ISSUE TITLE
the input format is non-sparse, could that be improved?

### ISSUE THREAD

**Issue by tanpuekai** [YosefLab/FastProject#11]
the current input format for your programme is row-col matrix, which contains huge numbers of zero

have u considered taking sparse format as input? like rowID<tab>colID<tab>expression, for expressions that are >0 ? and perhaps a gene-table containing rowID and corresponding gene symbols?

**Comment by deto** [comment]
This project isn't actively maintained anymore, however, the successor project (VISION) accepts sparse inputs and scales much better for large numbers of barcodes:

https://github.com/yoseflab/vision
