### ISSUE TITLE
Just calculate signatures

### ISSUE THREAD

**Issue by SamAllon** [YosefLab/FastProject#12]
Hi David, it's Sam Allon from the Shalek lab. Thanks for writing FastProject - I use it all the time!

I find myself using the weighted signature scores much more than the projections onto low-dimensional spaces. However, the latter seems to take up most of the runtime. Is there a way to flag the fastproject command to just calculate the signature scores?

Thanks!

**Comment by tiagobrc** [comment]
Hi David,
Congrats for this excellent software!
I am also interested in doing the weighted signature. Using your method gives me an error. 
Am I doing something wrong? Can you help?

This is what I did:

```
import pandas as pd
from FastProject.Interactive import estimate_weights, calculate_sig_scores
from FastProject.Signatures import read_signatures

signatures = read_signatures("/Users/tiagob/OneDrive/Mac Mucida/R_Projects/Sam Allon/Signatures/signatures.gmt")
data = pd.read_table("/Users/tiagob/OneDrive/Mac Mucida/R_Projects/Sam Allon/R/seurat_data.txt", index_col=0)

weights = estimate_weights(data)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tiagob/FastProject/lib/python2.7/site-packages/FastProject/Interactive.py", line 39, in estimate_weights
    expressionMatrix, housekeeping_genes)
TypeError: create_false_neg_map() takes at least 3 arguments (2 given)
```

Thanks!

**Comment by deto** [comment]
Fixed with d15b59acbda5c9079719f4b02bb3ea60b22357fd

**Comment by tiagobrc** [comment]
thanks for your help !
however after calling calculate_sig_scores I get another error:


```
>>> scores = calculate_sig_scores(data, weights, signatures)
|########################################| 100%
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tiagob/anaconda3/lib/python3.7/site-packages/FastProject/Interactive.py", line 183, in calculate_sig_scores
    all_scores = pd.concat(all_series, axis=1)
  File "/Users/tiagob/anaconda3/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 255, in concat
    sort=sort,
  File "/Users/tiagob/anaconda3/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 304, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
```

**Comment by deto** [comment]
Hi Tiago,

I think what might be happening is that the signatures are being discarded for not matching the row-labels (genes) in the data matrix.  Signature genes get upper-cased when they are read in (if you are using the read_signatures_gmt function) so if this is the case, the fix is to upper-case the genes in the expression dataframe row labels.  Give that a try!

Also, wanted to point you to the next iteration of this tool here (https://github.com/yoseflab/vision) though it's in R, not python :(
