### ISSUE TITLE
Signature Scores missing in Result File

### ISSUE THREAD

**Issue by JonasMir** [YosefLab/FastProject#13]
Dear all,

First of all I would like to thank you for the great tool you have developed since it is extremely useful for my work.  
However, for some custom gene lists I have the problem that in the final output /Expression/SignatureScores.txt, the row containing the signature scores is missing while the other two rows (FP_Quality and Zero_Proportion) are present with reasonable values. I checked many combinations of genes but I could not relate this problem to anything like list length, actual expression of list genes in the sample or comparable. Also I never get any warning in these cases while running the code. Do you have any ideas here?

Thanks for your answer in advance.

Best,

Jonas

**Comment by deto** [comment]
Hi Jonas - glad you find it useful!

There are two things that might be causing this.  First, the default behavior is to not output signatures that don't have significant autocorrelation (the thinking being to save space when there are thousands of tested signatures).  However, you can override that behavior by adding the `--all_sigs` flag when running.  Second, if these signatures have very few genes, they might be filtered for that reason (the idea being that, say, signatures matching only 5 genes in the data are likely to return spurious results).  However, you can tweak that with another flag, e.g. `--min_signature_genes 0`  to not filter signatures based on this.

Also, if you find this tool useful, you should check out its successor: https://github.com/yoseflab/vision which scales much better to large number of cells and has a greatly improved dynamic web report.

**Comment by JonasMir** [comment]
Hi David,

Thanks so much for your quick and helpful input. The newer tool I was indeed not aware of.  Unfortunately, setting both flags (even simultaneously) does not solve the problem in my case. Anyways, do you have any other idea or do you think it would be worth to give "vision" a try for these problematic lists?

Best,

Jonas

**Comment by deto** [comment]
I'm having a hard time thinking of what else might be causing this then.  Is it possible you could share the signature file with me? (either here, or if you prefer, email me at david.detomaso@berkeley.edu).  And let me know which ones aren't working out?

Though yeah, I'd definitely recommend giving VISION a try (if you are comfortable with R) as its more actively developed now.

**Comment by JonasMir** [comment]
So thanks again for your great support. You were entirely right: The additional option --nofilter solved the problem here since all genes seem to have undergone the outfiltering. For future computations I will switch to VISION though, as you have recommended!

Best,
Jonas
