### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by code837** [YosefLab/FastProject#8]
Hi-

I used FastProject with one signature file and after 1.5 hours received the below error message, 
can you help me troubleshoot this?

root@user-VirtualBox:/home/user/share/# fastproject data_v2.txt -s signatures_data_v2.gmt 
Loading data from data_v2.txt ...
WARNING: Row labels (gene identifiers) are not unique.
ABC2, ABC1
Removing these genes...
Imported  23685  genes across  4645  samples
Applying filter method: HDT
|########################################| 100%
Applying filter method: Fano

Estimating non-detect events

Correcting for false-negatives using housekeeping gene levels

Model:  Expression

Evaluating signature scores on samples...
|########################################| 100%

Evaluating null signature scores on samples...
|########################################| 100%

Filter-Level: Threshold

Projecting data into 2 dimensions
|----------------------------------------|   0%
Permutation test on wPCA:  11  components retained.
|########################################| 100%
Evaluating Clusters...
|########################################| 100%

Evaluating Signatures against Projections
|########################################| 100%
Projecting PC data into 2 dimensions
|########################################| 100%
Evaluating Clusters...
|########################################| 100%

Evaluating Signatures against Projections
|########################################| 100%

Filter-Level: HDT

Projecting data into 2 dimensions
|----------------------------------------|   0%Permutation test on wPCA:  10  components retained.
|##########------------------------------|  25%[t-SNE] Error: point (1.006690140e+02) is above right edge of node (1.006690063e+02)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/FastProject/CLI.py", line 237, in entry
    housekeeping_genes, input_projections, input_weights, args);
  File "/usr/local/lib/python2.7/dist-packages/FastProject/Pipelines.py", line 246, in Analysis
    input_projections, kwargs["lean"]);
  File "/usr/local/lib/python2.7/dist-packages/FastProject/Projections.py", line 87, in generate_projections
    result = method_list[method](proj_data, proj_weights);
  File "/usr/local/lib/python2.7/dist-packages/FastProject/Projections.py", line 436, in apply_tSNE10
    result = model.fit_transform(proj_data.T);
  File "/usr/local/lib/python2.7/dist-packages/sklearn/manifold/t_sne.py", line 884, in fit_transform
    embedding = self._fit(X)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/manifold/t_sne.py", line 789, in _fit
    skip_num_points=skip_num_points)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/manifold/t_sne.py", line 858, in _tsne
    params, error, it = _gradient_descent(obj_func, params, **opt_args)
  File "/usr/local/lib/python2.7/dist-packages/FastProject/_tsne_fix.py", line 84, in _gradient_descent
    new_error, grad = objective(p, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/manifold/t_sne.py", line 290, in _kl_divergence_bh
    dof=degrees_of_freedom)
  File "sklearn/manifold/_barnes_hut_tsne.pyx", line 780, in sklearn.manifold._barnes_hut_tsne.gradient (sklearn/manifold/_barnes_hut_tsne.c:8144)
**AssertionError: Tree consistency failed: unexpected number of points=4644 at root node=4645**

**Comment by deto** [comment]
I think this is due to a bug that's going on in the Barnes Hut tSNE code in scikit-learn.

-- https://github.com/scikit-learn/scikit-learn/issues/6683

From that thread, they recommend installing the development version of scikit-learn.  

`
pip install git+https://github.com/scikit-learn/scikit-learn.git@master --no-cache-dir
`

Can you try that?

**Comment by code837** [comment]
I received the following error message: 

user@user-VirtualBox:~$ pip install git+https://github.com/scikit-learn.git@master --no-cache-dir
Collecting git+https://github.com/scikit-learn.git@master
  Cloning https://github.com/scikit-learn.git (to master) to /tmp/pip-kVt18B-build
remote: Not Found
fatal: repository 'https://github.com/scikit-learn.git/' not found
Command "git clone -q https://github.com/scikit-learn.git /tmp/pip-kVt18B-build" failed with error code 128 in None

**Comment by deto** [comment]
There's two "scikit-learn"s in the address.  I think maybe you only entered one?

**Comment by code837** [comment]
I tried the code above, instead of re-typing, and I got a very long output log, 

Here is the top of it: 
user@user-VirtualBox:~$ pip install git+https://github.com/scikit-learn/scikit-learn.git@master --no-cache-dir
Collecting git+https://github.com/scikit-learn/scikit-learn.git@master
  Cloning https://github.com/scikit-learn/scikit-learn.git (to master) to /tmp/pip-UjYgWp-build
Installing collected packages: scikit-learn
  Running setup.py install for scikit-learn ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-UjYgWp-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-FuKx_G-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    Partial import of sklearn during the build process.
    blas_opt_info:
    blas_mkl_info:
      libraries mkl_rt not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
      NOT AVAILABLE
    
    blis_info:
      libraries blis not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
      NOT AVAILABLE
    
    openblas_info:
      libraries openblas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
      NOT AVAILABLE
    
    atlas_3_10_blas_threads_info:
    Setting PTATLAS=ATLAS
      libraries tatlas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
      NOT AVAILABLE
    
    atlas_3_10_blas_info:
      libraries satlas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
      NOT AVAILABLE
    
    atlas_blas_threads_info:
    Setting PTATLAS=ATLAS
      libraries ptf77blas,ptcblas,atlas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
      NOT AVAILABLE
    
    atlas_blas_info:
      libraries f77blas,cblas,atlas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
      NOT AVAILABLE

The rest of the error messages are tied to blas and the others mentioned above.

**Comment by deto** [comment]
Actually, it looks like the fixed version of scikit-learn has been released (in July).  Try running a `sudo pip install scikit-learn --upgrade`
