### ISSUE TITLE
runtimeerrors

### ISSUE THREAD

**Issue by kevin199011** [YosefLab/FastProject#9]
Hi, I was running single cell data on MsigDB and got the following error:
Traceback (most recent call last):
  File "/Users/kevinma/anaconda/lib/python3.5/site-packages/FastProject/CLI.py", line 252, in entry
    housekeeping_genes, input_projections, input_weights, args);
  File "/Users/kevinma/anaconda/lib/python3.5/site-packages/FastProject/Pipelines.py", line 373, in Analysis
    for name, sig_score in signatureScores.items():
RuntimeError: dictionary changed size during iteration

Could you please let me know how to solve this? Thank you!

Kevin

**Comment by deto** [comment]
Hey Kevin - what version are you running? I'm not seeing a line 373 in Pipelines.py in the most recent version.  I think I remember that issue and fixed it in a commit a few months back:

https://github.com/YosefLab/FastProject/commit/537c1934d0434cf7d04f26cce6104d4e29f86752#diff-0cb8c1f58861b9e0d069f8bd35bfd067

Try updating the module: `pip install fastproject --upgrade` and see if that fixes it.
